---
- name: Add ppa:webupd8team/java
  become: true
  apt_repository:
    repo: 'ppa:webupd8team/java'

- name: Accept oracle license
  become: true
  debconf:
    name: oracle-java9-installer
    question: shared/accepted-oracle-license-v1-1
    value: "true"
    vtype: select

- name: Install oracle java9
  become: true
  apt:
    name: oracle-java9-installer
    state: present

- name: Add JAVA_HOME variable
  become: true
  lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME="/usr/lib/jvm/java-8-oracle/"'
