---
- name: get the username running the deploy
  local_action: command whoami
  register: username_on_the_host
  changed_when: false

- import_tasks: manage_packages.yml
- import_tasks: install-oracle-java.yml
- import_tasks: setup_bash.yml
- import_tasks: install-spotify.yml
