---
- name: install packages
  become: True
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - python3-apt
    - debconf-utils
    - maven
    - htop
    - nano
    - kolourpaint4
    - npm
    - nodejs
    - python-pip
