---
- name: install packages
  become: true
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - python3-apt
    - debconf-utils
    - maven
    - htop
    - nano
    - kolourpaint4
    - python-pip

# Blacklist the nouveau driver module
#- name: Blacklist the nouveau driver module
#  become: true
#  kernel_blacklist:
#    blacklist_file: /etc/modprobe.d/blacklist.conf
#    name: nouveau
#    state: present
