---
- name: Configure bash
  copy:
    src: "{{ item }}"
    dest: "/home/{{ username_on_the_host.stdout }}/"
    owner: "{{ username_on_the_host.stdout }}"
  register: bash_configure
  with_fileglob:
    - ".*"

- name: Source bash files
  shell: ". /home/{{ username_on_the_host.stdout }}/{{ item | basename }}"
  when: bash_configure.changed
  with_fileglob:
    - ".*"
