---
- hosts: localhost
  become: true
  tags: docker
  roles:
    - role: docker
      # The local user name is available in this variable
      docker_user: "{{ansible_user_id}}"
    - role: gantsign.intellij
      intellij_edition: ultimate 
- hosts: localhost
  become: false
  roles:
    - common-dev-setup
