---

- name: Install and manage Nginx, mariadb and php
  hosts: lenovo
  become: True

  roles:
    - role: common-server
    - role: nginx
    - role: letsencrypt
    - role: mariadb
    - role: docker
