---
- name: Add apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0xcbcb082a1bb943db"

- name: Add mariadb repository
  apt_repository:
    repo: deb http://ftp.osuosl.org/pub/mariadb/repo/10.0/ubuntu trusty main
    state: present

- name: Install mariadb
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mariadb_dependecies }}"

- name: Create database user
  mysql_user:
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
