---
- name: Install Docker with Apt
  apt:
    name: docker-ce
    state: installed

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true

- name: Add the running user to the docker group
  user:
    name: "{{ docker_user }}"
    groups: ["docker"]
    append: yes
    state: present
