---
# See: https://docs.docker.com/engine/installation/linux/ubuntu/
- name: Install Prerequisites for Ubuntu
  apt:
    name: "{{item}}"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    state: present

- name: Install Docker Apt Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu xenial stable"
    state: present
    update_cache: true
