---
- import_tasks: install_docker_repository.yml

- import_tasks: install_and_enable_docker.yml

- import_tasks: install_docker_compose.yml

- import_tasks: registry.yml
  when: inventory_hostname != "localhost"
