---
- name: Add certbot repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present
    update_cache: yes
    filename: 'certbot'

- name: Install certbot-nginx and dependencies
  apt:
    name: 'python-certbot-nginx'
    state: installed

- name: Setup crontab
  lineinfile:
    path: /var/spool/cron/crontabs/root
    regexp: /usr/bin/certbot
    line: 15 3 * * * /usr/bin/certbot renew --quiet
